/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface AudioPlayer {
        "mediaStream": MediaStream;
    }
    interface CallPage {
        "roomname": string;
    }
    interface JoinCall {
    }
    interface NewCallPage {
    }
    interface TextField {
        "onChangeCallback": (value: string) => void;
        "value": string;
    }
}
declare global {
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAudioPlayerElement extends Components.AudioPlayer, HTMLStencilElement {
    }
    var HTMLAudioPlayerElement: {
        prototype: HTMLAudioPlayerElement;
        new (): HTMLAudioPlayerElement;
    };
    interface HTMLCallPageElement extends Components.CallPage, HTMLStencilElement {
    }
    var HTMLCallPageElement: {
        prototype: HTMLCallPageElement;
        new (): HTMLCallPageElement;
    };
    interface HTMLJoinCallElement extends Components.JoinCall, HTMLStencilElement {
    }
    var HTMLJoinCallElement: {
        prototype: HTMLJoinCallElement;
        new (): HTMLJoinCallElement;
    };
    interface HTMLNewCallPageElement extends Components.NewCallPage, HTMLStencilElement {
    }
    var HTMLNewCallPageElement: {
        prototype: HTMLNewCallPageElement;
        new (): HTMLNewCallPageElement;
    };
    interface HTMLTextFieldElement extends Components.TextField, HTMLStencilElement {
    }
    var HTMLTextFieldElement: {
        prototype: HTMLTextFieldElement;
        new (): HTMLTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "audio-player": HTMLAudioPlayerElement;
        "call-page": HTMLCallPageElement;
        "join-call": HTMLJoinCallElement;
        "new-call-page": HTMLNewCallPageElement;
        "text-field": HTMLTextFieldElement;
    }
}
declare namespace LocalJSX {
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppProfile {
    }
    interface AppRoot {
    }
    interface AudioPlayer {
        "mediaStream"?: MediaStream;
    }
    interface CallPage {
        "roomname"?: string;
    }
    interface JoinCall {
    }
    interface NewCallPage {
    }
    interface TextField {
        "onChangeCallback"?: (value: string) => void;
        "value"?: string;
    }
    interface IntrinsicElements {
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "audio-player": AudioPlayer;
        "call-page": CallPage;
        "join-call": JoinCall;
        "new-call-page": NewCallPage;
        "text-field": TextField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "audio-player": LocalJSX.AudioPlayer & JSXBase.HTMLAttributes<HTMLAudioPlayerElement>;
            "call-page": LocalJSX.CallPage & JSXBase.HTMLAttributes<HTMLCallPageElement>;
            "join-call": LocalJSX.JoinCall & JSXBase.HTMLAttributes<HTMLJoinCallElement>;
            "new-call-page": LocalJSX.NewCallPage & JSXBase.HTMLAttributes<HTMLNewCallPageElement>;
            "text-field": LocalJSX.TextField & JSXBase.HTMLAttributes<HTMLTextFieldElement>;
        }
    }
}
